import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import 'antd/dist/reset.css';
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import Sidebar from "@/components/Sidebar";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"></link>
            <body
                className={`${inter.variable} ${jetbrainsMono.variable} antialiased font-sans`}
                style={{ fontFamily: 'var(--font-inter), system-ui, sans-serif' }}
            >
                <Toaster />
                <div className="flex h-screen overflow-hidden">
                    <Sidebar />
                    {children}

                </div>
            </body>
        </html>
    );
}
